import React, { useState } from 'react';
import { 
  X, 
  Sparkles, 
  Clock, 
  HardDrive, 
  BookOpen, 
  UserCheck, 
  Tag, 
  Layers,
  Copy,
  Check
} from 'lucide-react';

export default function DeepExplanationModal({
  isOpen,
  onClose,
  analysisData,
  isLoading,
  language
}) {
  const [perspective, setPerspective] = useState('eli5');
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const handleCopy = () => {
    if (!analysisData) return;
    const text = `# ${analysisData.title}\n\n${analysisData.summary}\n\nTime Complexity: ${analysisData.complexity?.time}\nSpace Complexity: ${analysisData.complexity?.space}`;
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/50 dark:bg-black/70 backdrop-blur-sm animate-fadeIn select-none">
      <div className="bg-white dark:bg-dark-900 border border-slate-200 dark:border-dark-750 rounded-2xl w-full max-w-4xl max-h-[90vh] flex flex-col shadow-2xl overflow-hidden transition-colors">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 bg-slate-50 dark:bg-dark-850 border-b border-slate-200 dark:border-dark-750">
          <div className="flex items-center space-x-3">
            <div className="p-2 rounded-xl bg-gradient-to-tr from-blue-600 to-indigo-600 shadow-md">
              <Sparkles className="w-5 h-5 text-yellow-300" />
            </div>
            <div>
              <h2 className="text-base font-bold text-slate-900 dark:text-slate-100 flex items-center space-x-2">
                <span>AI Deep Code Explanation</span>
                <span className="text-xs font-mono bg-blue-100 dark:bg-brand-cyan/20 text-blue-800 dark:text-brand-cyan px-2 py-0.5 rounded border border-blue-200 dark:border-brand-cyan/30">
                  {language.toUpperCase()}
                </span>
              </h2>
              <p className="text-xs text-slate-500 dark:text-slate-400">
                Generated by {analysisData?.engine || 'CodeLens Native AI Engine'}
              </p>
            </div>
          </div>

          <div className="flex items-center space-x-2">
            <button
              onClick={handleCopy}
              className="p-2 rounded-lg text-slate-500 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white hover:bg-slate-200 dark:hover:bg-dark-750 transition-colors cursor-pointer"
              title="Copy Summary"
            >
              {copied ? <Check className="w-4 h-4 text-emerald-600" /> : <Copy className="w-4 h-4" />}
            </button>
            <button
              onClick={onClose}
              className="p-2 rounded-lg text-slate-500 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white hover:bg-slate-200 dark:hover:bg-dark-750 transition-colors cursor-pointer"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Modal Body */}
        <div className="flex-1 overflow-y-auto p-6 space-y-6 select-text font-sans">
          {isLoading ? (
            <div className="py-16 flex flex-col items-center justify-center space-y-4">
              <div className="w-10 h-10 border-4 border-blue-600 dark:border-brand-cyan border-t-transparent rounded-full animate-spin"></div>
              <p className="text-sm font-medium text-slate-600 dark:text-slate-300">
                Analyzing syntax tree, algorithmic complexity, and execution semantics...
              </p>
            </div>
          ) : analysisData ? (
            <>
              {/* Algorithm Title & Summary */}
              <div className="bg-slate-50 dark:bg-dark-950/80 border border-slate-200 dark:border-dark-750 p-4 rounded-xl space-y-2">
                <div className="flex items-center justify-between flex-wrap gap-2">
                  <h3 className="text-lg font-bold text-slate-900 dark:text-white flex items-center space-x-2">
                    <BookOpen className="w-5 h-5 text-blue-600 dark:text-brand-cyan" />
                    <span>{analysisData.title}</span>
                  </h3>
                  <span className="text-xs font-semibold px-2.5 py-1 rounded-full bg-purple-100 dark:bg-purple-500/20 text-purple-800 dark:text-purple-300 border border-purple-200 dark:border-purple-500/30">
                    {analysisData.algorithmType}
                  </span>
                </div>
                <p className="text-sm text-slate-700 dark:text-slate-300 leading-relaxed">
                  {analysisData.summary}
                </p>
                {analysisData.tags && (
                  <div className="flex flex-wrap gap-1.5 pt-2">
                    {analysisData.tags.map((tag, idx) => (
                      <span key={idx} className="text-[11px] font-mono bg-white dark:bg-dark-850 text-slate-600 dark:text-slate-400 px-2 py-0.5 rounded border border-slate-200 dark:border-dark-750 flex items-center space-x-1">
                        <Tag className="w-2.5 h-2.5 text-blue-600 dark:text-brand-cyan" />
                        <span>{tag}</span>
                      </span>
                    ))}
                  </div>
                )}
              </div>

              {/* Time & Space Complexity Cards */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {/* Time Complexity */}
                <div className="bg-slate-50 dark:bg-dark-950/80 border border-slate-200 dark:border-dark-750 p-4 rounded-xl space-y-2">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center space-x-2">
                      <Clock className="w-4 h-4 text-blue-600 dark:text-brand-cyan" />
                      <span className="text-xs font-bold uppercase tracking-wider text-slate-700 dark:text-slate-300">Time Complexity</span>
                    </div>
                    <span className="text-base font-mono font-extrabold text-blue-700 dark:text-brand-cyan bg-blue-100 dark:bg-brand-cyan/10 px-2.5 py-0.5 rounded border border-blue-200 dark:border-brand-cyan/30">
                      {analysisData.complexity?.time || 'O(N)'}
                    </span>
                  </div>
                  <p className="text-xs text-slate-700 dark:text-slate-300 leading-relaxed">
                    {analysisData.complexity?.timeDetail}
                  </p>
                </div>

                {/* Space Complexity */}
                <div className="bg-slate-50 dark:bg-dark-950/80 border border-slate-200 dark:border-dark-750 p-4 rounded-xl space-y-2">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center space-x-2">
                      <HardDrive className="w-4 h-4 text-purple-600 dark:text-purple-400" />
                      <span className="text-xs font-bold uppercase tracking-wider text-slate-700 dark:text-slate-300">Space Complexity</span>
                    </div>
                    <span className="text-base font-mono font-extrabold text-purple-700 dark:text-purple-400 bg-purple-100 dark:bg-purple-500/10 px-2.5 py-0.5 rounded border border-purple-200 dark:border-purple-500/30">
                      {analysisData.complexity?.space || 'O(1)'}
                    </span>
                  </div>
                  <p className="text-xs text-slate-700 dark:text-slate-300 leading-relaxed">
                    {analysisData.complexity?.spaceDetail}
                  </p>
                </div>
              </div>

              {/* Teaching Perspectives: ELI5 vs Senior Engineer */}
              <div className="bg-slate-50 dark:bg-dark-950/80 border border-slate-200 dark:border-dark-750 rounded-xl p-4 space-y-3">
                <div className="flex items-center justify-between border-b border-slate-200 dark:border-dark-800 pb-2">
                  <span className="text-xs font-bold uppercase tracking-wider text-slate-700 dark:text-slate-300 flex items-center space-x-1.5">
                    <UserCheck className="w-4 h-4 text-emerald-600 dark:text-emerald-400" />
                    <span>Teaching Perspective</span>
                  </span>

                  {/* Toggle Tabs */}
                  <div className="flex items-center bg-white dark:bg-dark-900 border border-slate-200 dark:border-dark-750 rounded-lg p-0.5 text-xs font-medium">
                    <button
                      onClick={() => setPerspective('eli5')}
                      className={`px-3 py-1 rounded-md transition-all cursor-pointer ${
                        perspective === 'eli5'
                          ? 'bg-emerald-600 text-white font-bold shadow-xs'
                          : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white'
                      }`}
                    >
                      ELI5 (Beginner)
                    </button>
                    <button
                      onClick={() => setPerspective('senior')}
                      className={`px-3 py-1 rounded-md transition-all cursor-pointer ${
                        perspective === 'senior'
                          ? 'bg-purple-600 text-white font-bold shadow-xs'
                          : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white'
                      }`}
                    >
                      Senior Engineer
                    </button>
                  </div>
                </div>

                <div className="text-xs text-slate-700 dark:text-slate-300 leading-relaxed bg-white dark:bg-dark-900/60 p-3 rounded-lg border border-slate-200 dark:border-dark-800">
                  {perspective === 'eli5'
                    ? analysisData.perspectives?.eli5
                    : analysisData.perspectives?.senior}
                </div>
              </div>

              {/* Line-by-Line Breakdown Table */}
              {analysisData.lineByLine && analysisData.lineByLine.length > 0 && (
                <div className="space-y-3">
                  <h4 className="text-xs font-bold uppercase tracking-wider text-slate-700 dark:text-slate-300 flex items-center space-x-2">
                    <Layers className="w-4 h-4 text-blue-600 dark:text-brand-cyan" />
                    <span>Line-by-Line Execution Breakdown</span>
                  </h4>

                  <div className="border border-slate-200 dark:border-dark-750 rounded-xl overflow-hidden bg-slate-50 dark:bg-dark-950/80">
                    <div className="divide-y divide-slate-200 dark:divide-dark-800 max-h-72 overflow-y-auto">
                      {analysisData.lineByLine.map((item, idx) => (
                        <div key={idx} className="p-3 hover:bg-slate-100 dark:hover:bg-dark-900/50 transition-colors flex items-start space-x-3 text-xs">
                          {/* Line Number */}
                          <span className="font-mono font-bold text-blue-700 dark:text-brand-cyan bg-white dark:bg-dark-900 px-2 py-0.5 rounded border border-slate-200 dark:border-dark-750 flex-shrink-0">
                            L{item.line}
                          </span>

                          {/* Code and Explanation */}
                          <div className="flex-1 space-y-1">
                            <div className="flex items-center justify-between">
                              <code className="font-mono text-xs text-purple-800 dark:text-purple-300 font-semibold bg-white dark:bg-dark-900 px-1.5 py-0.5 rounded border border-slate-200 dark:border-transparent">
                                {item.code || '(empty)'}
                              </code>
                              <span className="text-[10px] font-mono text-slate-500 bg-white dark:bg-dark-900 px-1.5 py-0.5 rounded border border-slate-200 dark:border-transparent">
                                {item.role}
                              </span>
                            </div>
                            <p className="text-slate-700 dark:text-slate-300 leading-normal">{item.explanation}</p>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
              )}
            </>
          ) : (
            <div className="text-center py-12 text-slate-500 text-sm">
              Click "Deep AI Explain" to generate a comprehensive analysis.
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
